version: "3.8"
services:
  admin:
    image: node:${NODE_VERSION:-18}
    working_dir: /app

    volumes:
      - ../../admin:/app
      - ../../conf/admin.env:/app/.env
    user: ${CURRENT_UID:-1000}:${CURRENT_GID:-1000}

